# Generated by Django 3.2.7 on 2021-09-02 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imgfile', models.FileField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chores', models.CharField(max_length=200)),
                ('homework', models.CharField(max_length=200)),
                ('recreational', models.CharField(max_length=200)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='parenting.kid')),
            ],
        ),
    ]
