# Generated by Django 3.2.7 on 2021-09-02 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parenting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kid',
            old_name='imgfile',
            new_name='imagefile',
        ),
    ]
