# Generated by Django 3.2.7 on 2021-09-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parenting', '0002_rename_imgfile_kid_imagefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='imagefile',
        ),
        migrations.AddField(
            model_name='kid',
            name='image',
            field=models.ImageField(null=True, upload_to='img/%y', verbose_name=''),
        ),
    ]
