# Generated by Django 3.2.7 on 2021-09-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parenting', '0003_auto_20210902_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='image',
            field=models.ImageField(default='no pic', null=True, upload_to='img/%y', verbose_name=''),
        ),
    ]
