# Generated by Django 3.2.7 on 2021-09-02 17:24

from django.db import migrations


def seed(apps, schema_editor):
    Kid = apps.get_model('parenting', 'Kid')
    Todo = apps.get_model('parenting', 'Todo')
    first = Kid(name="JDah")
    second = Kid(name='MJ')
    third = Kid(name='Chase')
    fourth = Kid(name='Armani')
    first.save()
    second.save()
    third.save()
    fourth.save()

    Todo(kid=first, chores='Bathroom',
         homework='Math', recreational='Dance').save()
    Todo(kid=second, chores='Bedroom',
         homework='Spelling', recreational='Karate').save()
    Todo(kid=third, chores='Laundry', homework='None',
         recreational='Free Day').save()
    Todo(kid=fourth, chores='Dishes', homework='Geography',
         recreational='Basketball').save()


def fallow(apps, schema_editor):
    Kid = apps.get_model('parenting', 'Kid')
    Todo = apps.get_model('parenting', 'Todo')
    Kid.objects.all().delete()
    Todo.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('parenting', '0007_alter_kid_name'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
